### ISSUE TITLE
Error after click Deploy on Azure

### ISSUE THREAD

**Issue by cheahengsoon** [Azure/Cloud-Katana#1]
After click the Deploy on Azure, the Azure shown the error as below:

There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/Cloud-Catana/main/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below.

**Comment by Cyb3rWard0g** [comment]
Hello @cheahengsoon ! I am working on some of the scripts for the deployment and I will update that link. Thank you for letting me know.

**Comment by Cyb3rWard0g** [comment]
Hello @cheahengsoon , it all should be working fine now :) 

I fixed it in this commit: https://github.com/Azure/Cloud-Katana/commit/a482dc6a6f80a8585592899be6d2231ddcc84833

All the `Deploy Buttons` are working fine. Before deployment, please follow the Prepare and Deploy docs:

* https://cloud-katana.com/prepare.html
* https://cloud-katana.com/deploy/azure/arm.html

Thank you for testing the project :) Let me know if you have any questions.

Enjoy your weekend!
